### ISSUE TITLE
Set up different coverage reporter tool

### ISSUE THREAD

**Issue by BolajiOlajide** [BolajiOlajide/ng-faker#35]
At the moment, `codecov` requires contributors to be signed up to their platform to report coverage if they aren't collaborators on the project.

Saying every contributor should have a codecov account isn't going to be scalable, so looking into alternative ways of reporting coverage or fixing `codecov`

Probably make use of coveralls instead.

**Comment by rotimi-babalola** [comment]
Can we close this issue? @BolajiOlajide seems #43 by @oyinda-subair resolves this

**Comment by BolajiOlajide** [comment]
Yes it does.
It can be closed.

( https://www.andela.com/ ) Bolaji Olajide /  Andela.com ( https://www.andela.com/ )
*Software Developer* /  810.164.4645  /  @Andela ( https://twitter.com/andela )
Brilliance is evenly distributed.
This message contains confidential information intended solely for the use of the parties named above.
