### ISSUE TITLE
Add more data to current dataset.

### ISSUE THREAD

**Issue by BolajiOlajide** [BolajiOlajide/ng-faker#52]
## DESCRIPTION
Currently we have lots of *nigerian* names, streets and what have you. It'd be great to have much more so everyone has a plethora of data to choose from.

Contribute by raising a PR and adding names and other things you deem worthy.

## GUIDE
- Fork the repository and branch out to the develop branch
- Navigate to the [locale directory](https://github.com/BolajiOlajide/ng-faker/tree/master/lib/locales)
- Depending on the language locale you'd like to provide data for, select the corresponding directory, feel free to add a new locale if you're feeling adventurous.
**N.B** common data that are language-agnostic can be found in the `common` directory.
- Once you're done supplying data for the locale and sub-item of your choice.
- Feel free to add your github profile and avatar to the contributor list on the readme. The contributor list can be found [here](https://github.com/BolajiOlajide/ng-faker/blob/develop/README.md#contributors)

Thanks to @mykeels for pointing this out.

**Comment by mykeels** [comment]
Can you give a guide for people to add names?

**Comment by BolajiOlajide** [comment]
On it @mykeels
