### ISSUE TITLE
How the fake date can be generated?

### ISSUE THREAD

**Issue by ankitsalu** [BolajiOlajide/ng-faker#61]
How the fake date can be generated?

**Comment by ankitsalu** [comment]
How the fake date can be generated?

**Comment by BolajiOlajide** [comment]
sorry what fake date?

**Comment by ankitsalu** [comment]
I meant how can we generate random dates through this library...?

**Comment by BolajiOlajide** [comment]
The library doesn't currently generate fake date, check out the [README](https://github.com/BolajiOlajide/ng-faker/blob/develop/README.md) to see the kinds of data that can be generated with `ng-faker`

**Comment by ankitsalu** [comment]
Yeh that's what ....can it be done?

**Comment by BolajiOlajide** [comment]
Is this a feature request?

**Comment by ankitsalu** [comment]
Yeh...if that can be added then it's going to be useful...many thanks

**Comment by BolajiOlajide** [comment]
Alright. I'll take that into consideration with the team. Thanks

**Comment by BolajiOlajide** [comment]
@oyinda-subair @rotimi-babalola What do you think?

**Comment by oyinda-subair** [comment]
I don't think is it a priority at the moment @BolajiOlajide
